FROM ros:noetic
LABEL maintainer "Chia Ching Yen <ccyen@umich.edu>"
SHELL ["/bin/bash", "-c"]
ENV \
    DEBIAN_FRONTEND="nonintractive" \
    X11VNC_PASSWORD="raccoon"

RUN apt-get update && apt-get install -y \
    # Basic utilities
    iputils-ping \
    curl \
    git-all \
    # ROS packages
    ros-${ROS_DISTRO}-rosbridge-server \
    ros-${ROS_DISTRO}-tf2-web-republisher \
    ros-${ROS_DISTRO}-moveit \
    ros-${ROS_DISTRO}-moveit-resources-prbt-moveit-config \
    # RTABROS
    ros-${ROS_DISTRO}-rtabmap \
    ros-${ROS_DISTRO}-rtabmap-ros \
    # TODO: Move some of the following to package dependency
    ros-${ROS_DISTRO}-rqt \
    ros-${ROS_DISTRO}-rqt-graph \
    ros-${ROS_DISTRO}-rqt-common-plugins \
    ros-${ROS_DISTRO}-ros-control \
    ros-${ROS_DISTRO}-ros-controllers\
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/

RUN apt-get update && apt-get install -y \
    # VNC and desktop env
    xvfb x11vnc fluxbox gnome-terminal \
    # Params
    --fix-missing \
    && rm -rf /var/lib/apt/lists/

# Create local catkin workspace
ENV CATKIN_WS=/root/catkin_ws
RUN mkdir -p $CATKIN_WS/src
WORKDIR $CATKIN_WS/src

# Build and install RTABROS
RUN cd ${CATKIN_WS} \
    && git clone https://github.com/introlab/rtabmap.git rtabmap \
    && cd rtabmap/build \
    && cmake .. \
    && make -j6 \
    && sudo make install

# Initialize local catkin workspace
RUN cd ${CATKIN_WS}/src \
    && source /opt/ros/${ROS_DISTRO}/setup.bash \
    && apt-get update \
    # Update apt-get because its cache is always cleared after installs to keep image size down
    # ROS File Server
    # && git clone https://github.com/gramaziokohler/ros_file_server.git \
    # Official packages
    # && git clone https://github.com/ros-planning/moveit_calibration.git \
    # && git clone https://github.com/introlab/rtabmap_ros.git \
    # Install dependencies
    && cd $CATKIN_WS \
    # && rosdep install -y --from-paths . --ignore-src --rosdistro ${ROS_DISTRO} \
    # Build catkin workspace
    && catkin_make

# Always source ros_catkin_entrypoint.sh when launching bash (e.g. when attaching to container)
RUN echo "source /ros_catkin_entrypoint.sh" >> /root/.bashrc

COPY ./ros_catkin_entrypoint.sh /
RUN chmod +x /ros_catkin_entrypoint.sh

ENTRYPOINT ["/ros_catkin_entrypoint.sh"]
CMD ["bash"]